import type { VitalRegistryItem } from './types';

const groupFile = (group: string, file: string) => ({
  path: `src-v2/blocks/data-table/${group}/${file}`,
  target: `src/blocks/${group}/${file}`,
  type: 'registry:block' as const,
});

const cloudSidebarFiles = (name: string) => [
  {
    path: `src-v2/blocks/${name}/components/app-sidebar.tsx`,
    target: `src/blocks/${name}/app-sidebar.tsx`,
    type: 'registry:component' as const,
  },
  {
    path: 'src-v2/public/images/cloud.jpg',
    target: 'src/public/images/cloud.jpg',
    type: 'registry:file' as const,
  },
];

export const blocks: VitalRegistryItem[] = [
  {
    name: 'data-table-group-01',
    type: 'registry:block',
    title: 'Data Table — Candidate Tree',
    description:
      'Grouped tree-style data table with selectable rows, column pinning, action bar, and filter dropdown',
    categories: ['data-table'],
    dependencies: ['@tanstack/react-table', 'cn'],
    registryDependencies: [
      '@vital-design/utils',
      '@vital-design/avatar',
      '@vital-design/button',
      '@vital-design/card',
      '@vital-design/checkbox',
      '@vital-design/dropdown-menu',
      '@vital-design/progress',
      '@vital-design/search-bar',
      '@vital-design/table',
      '@vital-design/tag',
      '@vital-design/toolbar',
      '@vital-design/icon-chevron-down',
      '@vital-design/icon-ellipsis',
      '@vital-design/vital-theme',
    ],
    files: [
      groupFile('data-table-group-01', 'DataTableGroup01.tsx'),
      groupFile('data-table-group-01', 'action-bar.tsx'),
      groupFile('data-table-group-01', 'columns.tsx'),
      groupFile('data-table-group-01', 'data.ts'),
      groupFile('data-table-group-01', 'pinning.ts'),
    ],
  },
  {
    name: 'data-table-group-02',
    type: 'registry:block',
    title: 'Data Table — ESG Emission Tree',
    description:
      'Expandable tree data table with sticky rail, sortable headers, selection, action bar, and inline switch toggles',
    categories: ['data-table'],
    dependencies: ['@tanstack/react-table', 'cn'],
    registryDependencies: [
      '@vital-design/utils',
      '@vital-design/avatar',
      '@vital-design/badge',
      '@vital-design/button',
      '@vital-design/card',
      '@vital-design/checkbox',
      '@vital-design/dropdown-menu',
      '@vital-design/search-bar',
      '@vital-design/switch',
      '@vital-design/table',
      '@vital-design/tag',
      '@vital-design/toolbar',
      '@vital-design/icon-chevron-down',
      '@vital-design/icon-chevron-up',
      '@vital-design/icon-ellipsis',
      '@vital-design/vital-theme',
    ],
    files: [
      groupFile('data-table-group-02', 'DataTableGroup02.tsx'),
      groupFile('data-table-group-02', 'action-bar.tsx'),
      groupFile('data-table-group-02', 'columns.tsx'),
      groupFile(
        'data-table-group-02',
        'data-table-column-header.tsx',
      ),
      groupFile('data-table-group-02', 'data.ts'),
      groupFile('data-table-group-02', 'pinning.ts'),
      groupFile('data-table-group-02', 'table-rail.tsx'),
    ],
  },
  {
    name: 'data-table-group-04',
    type: 'registry:block',
    title: 'Data Table — Editable Cells',
    description:
      'Editable data table with inline text cells, popover pickers, tag multi-select, and date selection',
    categories: ['data-table'],
    dependencies: ['@tanstack/react-table', 'cn'],
    registryDependencies: [
      '@vital-design/utils',
      '@vital-design/avatar',
      '@vital-design/calendar',
      '@vital-design/card',
      '@vital-design/editable',
      '@vital-design/popover',
      '@vital-design/table',
      '@vital-design/tag',
      '@vital-design/icon-check',
      '@vital-design/vital-theme',
    ],
    files: [
      groupFile('data-table-group-04', 'DataTableGroup04.tsx'),
      groupFile('data-table-group-04', 'columns.tsx'),
      groupFile('data-table-group-04', 'data.ts'),
      groupFile('data-table-group-04', 'popover-edit.tsx'),
    ],
  },
  {
    name: 'sidebar-cloud-01',
    type: 'registry:block',
    title: 'Sidebar — Cloud Flat',
    description:
      'Base cloud sidebar: frosted glass, flat nav with no submenus, no account footer, active edge rail, bullet collapse. Installs CloudSidebar plus the frost photo. Compose SidebarProvider and SidebarInset in the app. Sample logos use /images public paths and are not shipped.',
    categories: ['sidebar', 'layout', 'navigation'],
    dependencies: ['cn'],
    registryDependencies: [
      '@vital-design/utils',
      '@vital-design/sidebar',
      '@vital-design/icon-calendar',
      '@vital-design/icon-check',
      '@vital-design/icon-flag',
      '@vital-design/icon-panel-left',
      '@vital-design/icon-search',
      '@vital-design/icon-user',
      '@vital-design/vital-theme',
    ],
    files: cloudSidebarFiles('sidebar-cloud-01'),
  },
  {
    name: 'sidebar-cloud-02',
    type: 'registry:block',
    title: 'Sidebar — Cloud Inline Submenus',
    description:
      'Cloud sidebar with inline nested nav, account footer, frosted glass, active edge rail, and bullet collapse. Installs CloudSidebar plus the frost photo. Compose SidebarProvider and SidebarInset in the app. Sample logos and avatar use /images public paths and are not shipped.',
    categories: ['sidebar', 'layout', 'navigation'],
    dependencies: ['cn'],
    registryDependencies: [
      '@vital-design/utils',
      '@vital-design/sidebar',
      '@vital-design/avatar',
      '@vital-design/dropdown-menu',
      '@vital-design/icon-calendar',
      '@vital-design/icon-check',
      '@vital-design/icon-flag',
      '@vital-design/icon-panel-left',
      '@vital-design/icon-search',
      '@vital-design/icon-user',
      '@vital-design/vital-theme',
    ],
    files: cloudSidebarFiles('sidebar-cloud-02'),
  },
  {
    name: 'sidebar-cloud-03',
    type: 'registry:block',
    title: 'Sidebar — Cloud Dropdown Submenus',
    description:
      'Cloud sidebar that opens nested items as a side dropdown, with a header Add action, frosted glass, and no account footer. Installs CloudSidebar plus the frost photo. Compose SidebarProvider and SidebarInset in the app. Sample logos use /images public paths and are not shipped.',
    categories: ['sidebar', 'layout', 'navigation'],
    dependencies: ['cn'],
    registryDependencies: [
      '@vital-design/utils',
      '@vital-design/sidebar',
      '@vital-design/button',
      '@vital-design/dropdown-menu',
      '@vital-design/icon-calendar',
      '@vital-design/icon-check',
      '@vital-design/icon-ellipsis',
      '@vital-design/icon-flag',
      '@vital-design/icon-panel-left',
      '@vital-design/icon-plus',
      '@vital-design/icon-search',
      '@vital-design/icon-user',
      '@vital-design/vital-theme',
    ],
    files: cloudSidebarFiles('sidebar-cloud-03'),
  },
  {
    name: 'sidebar-cloud-04',
    type: 'registry:block',
    title: 'Sidebar — Cloud Secondary Nav',
    description:
      'Cloud sidebar with flat main nav, secondary links pinned above an account footer, frosted glass, and bullet collapse. Installs CloudSidebar plus the frost photo. Compose SidebarProvider and SidebarInset in the app. Sample logos and avatar use /images public paths and are not shipped.',
    categories: ['sidebar', 'layout', 'navigation'],
    dependencies: ['cn'],
    registryDependencies: [
      '@vital-design/utils',
      '@vital-design/sidebar',
      '@vital-design/avatar',
      '@vital-design/dropdown-menu',
      '@vital-design/icon-calendar',
      '@vital-design/icon-check',
      '@vital-design/icon-flag',
      '@vital-design/icon-info',
      '@vital-design/icon-panel-left',
      '@vital-design/icon-search',
      '@vital-design/icon-shield-check',
      '@vital-design/icon-square-arrow-out-up-right',
      '@vital-design/icon-user',
      '@vital-design/vital-theme',
    ],
    files: cloudSidebarFiles('sidebar-cloud-04'),
  },
  {
    name: 'sidebar-cloud-05',
    type: 'registry:block',
    title: 'Sidebar — Cloud Header Actions',
    description:
      'Cloud sidebar with a mark-only logo, header search and notifications, flat nav, account footer, and frosted glass. Installs CloudSidebar plus the frost photo. Compose SidebarProvider and SidebarInset in the app. Sample logo and avatar use /images public paths and are not shipped.',
    categories: ['sidebar', 'layout', 'navigation'],
    dependencies: ['cn'],
    registryDependencies: [
      '@vital-design/utils',
      '@vital-design/sidebar',
      '@vital-design/avatar',
      '@vital-design/badge',
      '@vital-design/button',
      '@vital-design/dropdown-menu',
      '@vital-design/icon-bell',
      '@vital-design/icon-calendar',
      '@vital-design/icon-check',
      '@vital-design/icon-flag',
      '@vital-design/icon-panel-left',
      '@vital-design/icon-search',
      '@vital-design/icon-user',
      '@vital-design/vital-theme',
    ],
    files: cloudSidebarFiles('sidebar-cloud-05'),
  },
  {
    name: 'sidebar-cloud-06',
    type: 'registry:block',
    title: 'Sidebar — Cloud Collapsible Submenus',
    description:
      'Cloud sidebar with collapsible inline nested nav, account footer, frosted glass, and bullet collapse. Installs CloudSidebar plus the frost photo. Compose SidebarProvider and SidebarInset in the app. Sample logos and avatar use /images public paths and are not shipped.',
    categories: ['sidebar', 'layout', 'navigation'],
    dependencies: ['cn'],
    registryDependencies: [
      '@vital-design/utils',
      '@vital-design/sidebar',
      '@vital-design/avatar',
      '@vital-design/collapsible',
      '@vital-design/dropdown-menu',
      '@vital-design/icon-calendar',
      '@vital-design/icon-check',
      '@vital-design/icon-chevron-right',
      '@vital-design/icon-flag',
      '@vital-design/icon-panel-left',
      '@vital-design/icon-search',
      '@vital-design/icon-user',
      '@vital-design/vital-theme',
    ],
    files: cloudSidebarFiles('sidebar-cloud-06'),
  },
];
