// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — .source/ is auto-generated by fumadocs-mdx during build
import { loader } from 'fumadocs-core/source';
import { createMDXSource } from 'fumadocs-mdx';
import { docs } from '../.source';

export const source = loader({
  baseUrl: '/docs',
  // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-member-access
  source: createMDXSource((docs as any).docs, (docs as any).meta),
});
