export const testData = [
  {
    label: '',
    data: [
      {
        displayName: '上一關簽核主管',
        subjectId: '-3',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: undefined,
      },
      {
        displayName: '本關簽核人主管',
        subjectId: '-2',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: undefined,
      },
      {
        displayName: '起單人的主管',
        subjectId: '-1',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: undefined,
      },
    ],
  },
  {
    label: '',
    data: [
      {
        displayName: '所有人',
        subjectId: '0',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [
          {
            displayName: '成員1',
            subjectId: '1',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
            isAdmin: true,
          },
          {
            displayName: '成員2',
            subjectId: '2',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員3',
            subjectId: '3',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員4',
            subjectId: '4',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員5',
            subjectId: '5',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員6',
            subjectId: '6',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員7',
            subjectId: '7',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員8',
            subjectId: '8',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員9',
            subjectId: '9',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員10',
            subjectId: '10',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員11',
            subjectId: '11',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
        ],
      },
      {
        displayName: '未分配成員',
        subjectId: '12',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [
          {
            displayName: '成員1',
            subjectId: '13',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
            isAdmin: true,
          },
          {
            displayName: '成員2',
            subjectId: '14',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
        ],
      },
    ],
  },
  {
    label: '組織',
    data: [
      {
        displayName: '組織1',
        subjectId: '15',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [
          {
            displayName: '成員1',
            subjectId: '16',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員2',
            subjectId: '17',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員3',
            subjectId: '18',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
        ],
      },
      {
        displayName: '組織2',
        subjectId: '19',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [
          {
            displayName: '成員1',
            subjectId: '20',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員2',
            subjectId: '21',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員3',
            subjectId: '22',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
        ],
      },
      {
        displayName: '組織3 (無成員)',
        subjectId: 'og3',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [],
      },
    ],
  },
  {
    label: '群組',
    data: [
      {
        displayName: '群組 (無成員)',
        subjectId: 'group-no-user',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [],
      },
      {
        displayName: '群組1',
        subjectId: '23',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [
          {
            displayName: '成員1',
            subjectId: '24',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員2',
            subjectId: '25',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員3',
            subjectId: '26',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
        ],
      },
      {
        displayName: '群組2',
        subjectId: '27',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [
          {
            displayName: '成員1',
            subjectId: '28',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員2',
            subjectId: '29',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員3',
            subjectId: '30',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
        ],
      },
      {
        displayName: '群組3',
        subjectId: '31',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [
          {
            displayName: '成員1',
            subjectId: '32',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員2',
            subjectId: '33',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員3',
            subjectId: '34',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
        ],
      },
      {
        displayName: '群組4',
        subjectId: '35',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [
          {
            displayName: '成員1',
            subjectId: '36',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員2',
            subjectId: '37',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員3',
            subjectId: '38',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
        ],
      },
      {
        displayName: '群組5',
        subjectId: '39',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [
          {
            displayName: '成員1',
            subjectId: '40',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員2',
            subjectId: '41',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員3',
            subjectId: '42',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
        ],
      },
      {
        displayName: '群組6',
        subjectId: '43',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [
          {
            displayName: '成員1',
            subjectId: '44',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員2',
            subjectId: '45',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員3',
            subjectId: '46',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
        ],
      },
      {
        displayName: '群組7',
        subjectId: '47',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [
          {
            displayName: '成員1',
            subjectId: '48',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員2',
            subjectId: '49',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員3',
            subjectId: '50',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
        ],
      },
      {
        displayName: '群組8',
        subjectId: '51',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [
          {
            displayName: '成員1',
            subjectId: '52',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員2',
            subjectId: '53',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員3',
            subjectId: '54',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
        ],
      },
      {
        displayName: '群組9',
        subjectId: '55',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [
          {
            displayName: '成員1',
            subjectId: '56',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員2',
            subjectId: '57',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員3',
            subjectId: '58',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
        ],
      },
      {
        displayName: '群組10',
        subjectId: '59',
        subjectType: 1,
        parents: [],
        createdAt: '1',
        updatedAt: '1',
        children: [
          {
            displayName: '成員1',
            subjectId: '60',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員2',
            subjectId: '61',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
          {
            displayName: '成員3',
            subjectId: '62',
            subjectType: 2,
            parents: [],
            createdAt: '1',
            updatedAt: '1',
          },
        ],
      },
    ],
  },
];
