#!/usr/bin/env tsx
import { mkdirSync } from 'fs';
import { resolve } from 'path';
import SD from 'style-dictionary';
import type { TransformedToken } from 'style-dictionary/types';

// Ensure output directory exists
mkdirSync(resolve('src-v2/styles/tokens'), { recursive: true });

// ── Helpers ──────────────────────────────────────────────────────────────────

function isColor(token: TransformedToken): boolean {
  return token.$type === 'color';
}

function quoteValue(v: string): string {
  return v.includes("'") ? `"${v}"` : `'${v}'`;
}

// ── Config ────────────────────────────────────────────────────────────────────

const sd = new SD({
  log: { verbosity: 'silent' },
  source: ['tokens/**/*.json'],
  hooks: {
    transforms: {
      // Drops a leading `theme.` segment from semantic shadcn tokens so they
      // emit unprefixed names (e.g. `theme.primary` → `--primary`). This lets
      // semantic slots coexist with primitive scales like `--primary-500` in a
      // single Style Dictionary tree without path collision.
      'name/vital-kebab': {
        type: 'name',
        transitive: true,
        transform: (token) => {
          const parts =
            token.path[0] === 'theme'
              ? token.path.slice(1)
              : token.path;
          return parts.join('-');
        },
      },
    },
    formats: {
      // Outputs: :root { --name: value } + @theme inline { --color-name: var(--name); --name: value; }
      'css/vital-tokens': ({ dictionary }) => {
        const colorTokens = dictionary.allTokens.filter(isColor);
        const nonColorTokens = dictionary.allTokens.filter(
          (t) => !isColor(t),
        );

        const rootVars = colorTokens
          .map((t) => `  --${t.name}: ${t.$value};`)
          .join('\n');

        const themeColorMappings = colorTokens
          .map((t) => `  --color-${t.name}: var(--${t.name});`)
          .join('\n');

        const themeNonColorVars = nonColorTokens
          .map((t) => `  --${t.name}: ${t.$value};`)
          .join('\n');

        return [
          '/* Auto-generated by Style Dictionary. Do not edit manually. */',
          '/* Run `pnpm registry:build` to regenerate. */',
          '',
          ':root {',
          rootVars,
          '}',
          '',
          '@theme inline {',
          themeColorMappings,
          themeNonColorVars,
          '}',
          '',
        ].join('\n');
      },

      // Outputs: export const vitalThemeCssVars = { theme: {...}, light: {...} } as const
      'typescript/vital-theme-vars': ({ dictionary }) => {
        const colorTokens = dictionary.allTokens.filter(isColor);
        const nonColorTokens = dictionary.allTokens.filter(
          (t) => !isColor(t),
        );

        const lightEntries = colorTokens
          .map(
            (t) =>
              `    '${t.name}': ${quoteValue(String(t.$value))},`,
          )
          .join('\n');

        const themeEntries = nonColorTokens
          .map(
            (t) =>
              `    '${t.name}': ${quoteValue(String(t.$value))},`,
          )
          .join('\n');

        return [
          '// This file is auto-generated by Style Dictionary.',
          '// Do not edit manually — run `pnpm registry:build` to regenerate.',
          '',
          'export const vitalThemeCssVars = {',
          '  theme: {',
          themeEntries,
          '  },',
          '  light: {',
          lightEntries,
          '  },',
          '} as const;',
          '',
        ].join('\n');
      },
    },
  },
  platforms: {
    css: {
      transforms: ['name/vital-kebab'],
      buildPath: 'src-v2/styles/tokens/',
      files: [
        { format: 'css/vital-tokens', destination: 'generated.css' },
      ],
    },
    registry: {
      transforms: ['name/vital-kebab'],
      buildPath: 'registry/',
      files: [
        {
          format: 'typescript/vital-theme-vars',
          destination: 'vital-theme-vars.ts',
        },
      ],
    },
  },
});

const availablePlatforms = ['css', 'registry'] as const;
type BuildPlatform = (typeof availablePlatforms)[number];

const requestedPlatforms = process.argv.slice(2);

if (requestedPlatforms.length > 0) {
  for (const platform of requestedPlatforms) {
    if (!availablePlatforms.includes(platform as BuildPlatform)) {
      throw new Error(`Unknown token build platform: ${platform}`);
    }
  }

  for (const platform of requestedPlatforms) {
    await sd.buildPlatform(platform as BuildPlatform);
  }
} else {
  await sd.buildAllPlatforms();
}

console.log('✔ tokens built');
