export interface Emission {
  id: number;
  source: string;
  formula: string;
  count: number;
  owner: string;
  reviewer: string;
  template: string;
  reference: string | null;
  tag: string | null;
  quantified: boolean;
  category: string;
  subcategory: string;
}

export type EmissionTreeRow =
  | {
      id: string;
      kind: 'category';
      title: string;
      subRows: EmissionTreeRow[];
    }
  | {
      id: string;
      kind: 'subcategory';
      title: string;
      subRows: EmissionTreeRow[];
    }
  | (Emission & {
      kind: 'source';
    });

export const emissions: Emission[] = [
  {
    id: 1,
    source: '緊急發電機(柴油)',
    formula: '柴油(固)',
    count: 3,
    owner: '張',
    reviewer: '張',
    template: '自訂欄位',
    reference: '車用汽…',
    tag: '電力',
    quantified: true,
    category: '類別1：直接',
    subcategory: '1.1 固定燃燒之直接排放',
  },
  {
    id: 2,
    source: '公務車(汽油)',
    formula: '車用汽油(移)-氧化觸媒',
    count: 3,
    owner: '張',
    reviewer: '張',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別1：直接',
    subcategory: '1.1 固定燃燒之直接排放',
  },
  {
    id: 3,
    source: '鍋爐(天然氣)',
    formula: '天然氣(固)',
    count: 2,
    owner: '張',
    reviewer: '蔡',
    template: '自訂欄位',
    reference: null,
    tag: '燃料',
    quantified: true,
    category: '類別1：直接',
    subcategory: '1.1 固定燃燒之直接排放',
  },
  {
    id: 4,
    source: '備援發電機(LPG)',
    formula: 'LPG(固)',
    count: 1,
    owner: '林',
    reviewer: '張',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別1：直接',
    subcategory: '1.1 固定燃燒之直接排放',
  },
  {
    id: 5,
    source: '公務車(柴油)',
    formula: '車用柴油(移)',
    count: 4,
    owner: '張',
    reviewer: '張',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別1：直接',
    subcategory: '1.2 移動燃燒之直接排放',
  },
  {
    id: 6,
    source: '堆高機(LPG)',
    formula: '車用LPG(移)',
    count: 2,
    owner: '林',
    reviewer: '張',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別1：直接',
    subcategory: '1.2 移動燃燒之直接排放',
  },
  {
    id: 7,
    source: '製程排放_化學反應',
    formula: '碳酸鈣分解',
    count: 1,
    owner: '蔡',
    reviewer: '張',
    template: '自訂欄位',
    reference: null,
    tag: '製程',
    quantified: true,
    category: '類別1：直接',
    subcategory: '1.3 製程之直接排放',
  },
  {
    id: 8,
    source: '公務車空調_R-134A',
    formula: '車輛空調冷媒_HFC-134a/R-134a…',
    count: 3,
    owner: '張',
    reviewer: '張',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別1：直接',
    subcategory: '1.4 逸散源之直接排放',
  },
  {
    id: 9,
    source: '滅火器(CO2)',
    formula: '滅火器(CO2)',
    count: 3,
    owner: '未指派',
    reviewer: '未指派',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: false,
    category: '類別1：直接',
    subcategory: '1.4 逸散源之直接排放',
  },
  {
    id: 10,
    source: '中央空調冷媒_R-410A',
    formula: 'HFC-410A',
    count: 2,
    owner: '蔡',
    reviewer: '張',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別1：直接',
    subcategory: '1.4 逸散源之直接排放',
  },
  {
    id: 11,
    source: '冰水主機冷媒_R-407C',
    formula: 'HFC-407C',
    count: 2,
    owner: '蔡',
    reviewer: '張',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別1：直接',
    subcategory: '1.4 逸散源之直接排放',
  },
  {
    id: 12,
    source: '化糞池甲烷排放',
    formula: 'CH4 排放係數',
    count: 1,
    owner: '林',
    reviewer: '蔡',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: false,
    category: '類別1：直接',
    subcategory: '1.5 土地利用之直接排放',
  },
  {
    id: 13,
    source: '外購電力',
    formula: '台電',
    count: 3,
    owner: '未指派',
    reviewer: '未指派',
    template: '台電電費單',
    reference: null,
    tag: '綠電',
    quantified: true,
    category: '類別2：能源間接',
    subcategory: '2.1 輸入電力之間接排放',
  },
  {
    id: 14,
    source: '再生能源憑證(T-REC)',
    formula: '台電',
    count: 2,
    owner: '張',
    reviewer: '蔡',
    template: '台電電費單',
    reference: null,
    tag: '綠電',
    quantified: true,
    category: '類別2：能源間接',
    subcategory: '2.1 輸入電力之間接排放',
  },
  {
    id: 15,
    source: '外購蒸氣',
    formula: '工業蒸氣',
    count: 1,
    owner: '蔡',
    reviewer: '張',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別2：能源間接',
    subcategory: '2.2 輸入蒸氣之間接排放',
  },
  {
    id: 16,
    source: '區域冷卻系統',
    formula: '區域冷能(kWh)',
    count: 1,
    owner: '林',
    reviewer: '張',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: false,
    category: '類別2：能源間接',
    subcategory: '2.3 輸入冷能之間接排放',
  },
  {
    id: 17,
    source: '原物料運輸_海運',
    formula: '海運貨櫃(TEU‑km)',
    count: 4,
    owner: '陳',
    reviewer: '張',
    template: '自訂欄位',
    reference: null,
    tag: '上游',
    quantified: true,
    category: '類別3：運輸的間接排放',
    subcategory: '3.1 上游運輸與配送',
  },
  {
    id: 18,
    source: '原物料運輸_陸運',
    formula: '貨車(t‑km)',
    count: 5,
    owner: '陳',
    reviewer: '張',
    template: '自訂欄位',
    reference: null,
    tag: '上游',
    quantified: true,
    category: '類別3：運輸的間接排放',
    subcategory: '3.1 上游運輸與配送',
  },
  {
    id: 19,
    source: '成品配送_冷鏈',
    formula: '冷鏈貨車(t‑km)',
    count: 3,
    owner: '陳',
    reviewer: '蔡',
    template: '自訂欄位',
    reference: null,
    tag: '下游',
    quantified: true,
    category: '類別3：運輸的間接排放',
    subcategory: '3.2 下游運輸與配送',
  },
  {
    id: 20,
    source: '員工通勤',
    formula: '通勤平均(人‑km)',
    count: 1,
    owner: '未指派',
    reviewer: '未指派',
    template: '員工調查',
    reference: null,
    tag: null,
    quantified: false,
    category: '類別3：運輸的間接排放',
    subcategory: '3.3 員工通勤',
  },
  {
    id: 21,
    source: '商務差旅_國內航班',
    formula: '短程航班(人‑km)',
    count: 2,
    owner: '陳',
    reviewer: '張',
    template: '差旅報銷',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別3：運輸的間接排放',
    subcategory: '3.4 商務差旅',
  },
  {
    id: 22,
    source: '商務差旅_國際航班',
    formula: '長程航班(人‑km)',
    count: 2,
    owner: '陳',
    reviewer: '張',
    template: '差旅報銷',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別3：運輸的間接排放',
    subcategory: '3.4 商務差旅',
  },
  {
    id: 23,
    source: '採購原料_鋼材',
    formula: 'EPD - 鋼材',
    count: 3,
    owner: '陳',
    reviewer: '蔡',
    template: '採購單',
    reference: '車用汽…',
    tag: '上游',
    quantified: true,
    category: '類別4：產品使用之間接排放',
    subcategory: '4.1 採購之商品與服務',
  },
  {
    id: 24,
    source: '採購原料_鋁材',
    formula: 'EPD - 鋁',
    count: 2,
    owner: '陳',
    reviewer: '蔡',
    template: '採購單',
    reference: null,
    tag: '上游',
    quantified: true,
    category: '類別4：產品使用之間接排放',
    subcategory: '4.1 採購之商品與服務',
  },
  {
    id: 25,
    source: '採購原料_包材紙箱',
    formula: 'EPD - 紙箱',
    count: 4,
    owner: '陳',
    reviewer: '張',
    template: '採購單',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別4：產品使用之間接排放',
    subcategory: '4.1 採購之商品與服務',
  },
  {
    id: 26,
    source: '資本財_機台設備',
    formula: 'EPD - 機台',
    count: 1,
    owner: '未指派',
    reviewer: '未指派',
    template: '採購單',
    reference: null,
    tag: null,
    quantified: false,
    category: '類別4：產品使用之間接排放',
    subcategory: '4.2 資本財',
  },
  {
    id: 27,
    source: '租賃辦公設備',
    formula: '租賃資產活動數據',
    count: 2,
    owner: '林',
    reviewer: '張',
    template: '租賃契約',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別4：產品使用之間接排放',
    subcategory: '4.3 上游租賃資產',
  },
  {
    id: 28,
    source: '產品使用階段_耗電',
    formula: '使用週期(kWh)',
    count: 5,
    owner: '蔡',
    reviewer: '陳',
    template: '自訂欄位',
    reference: null,
    tag: '下游',
    quantified: true,
    category: '類別5：產品最終處置之間接排放',
    subcategory: '5.1 售出產品之使用',
  },
  {
    id: 29,
    source: '產品報廢_焚化處理',
    formula: '產品末端處置 - 焚化',
    count: 3,
    owner: '陳',
    reviewer: '蔡',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別5：產品最終處置之間接排放',
    subcategory: '5.2 售出產品之最終處置',
  },
  {
    id: 30,
    source: '產品報廢_掩埋處理',
    formula: '產品末端處置 - 掩埋',
    count: 2,
    owner: '陳',
    reviewer: '蔡',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: false,
    category: '類別5：產品最終處置之間接排放',
    subcategory: '5.2 售出產品之最終處置',
  },
  {
    id: 31,
    source: '產品回收_鋁罐',
    formula: '回收係數 - 鋁',
    count: 2,
    owner: '陳',
    reviewer: '蔡',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別5：產品最終處置之間接排放',
    subcategory: '5.3 售出產品之回收再製',
  },
  {
    id: 32,
    source: '投資組合_股權投資',
    formula: 'PCAF - 上市股票',
    count: 1,
    owner: '未指派',
    reviewer: '未指派',
    template: '投資組合',
    reference: null,
    tag: null,
    quantified: false,
    category: '類別6：其他間接排放',
    subcategory: '6.1 投資',
  },
  {
    id: 33,
    source: '加盟業主能源使用',
    formula: '加盟分店活動數據',
    count: 4,
    owner: '林',
    reviewer: '張',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別6：其他間接排放',
    subcategory: '6.2 加盟與授權',
  },
  {
    id: 34,
    source: '營運廢棄物_一般事業廢棄物',
    formula: '一般事業廢棄物(噸)',
    count: 3,
    owner: '林',
    reviewer: '蔡',
    template: '自訂欄位',
    reference: null,
    tag: null,
    quantified: true,
    category: '類別6：其他間接排放',
    subcategory: '6.3 廢棄物處理',
  },
];

export function getEmissionLeaves(row: EmissionTreeRow): Emission[] {
  if (row.kind === 'source') {
    return [row];
  }

  return row.subRows.flatMap(getEmissionLeaves);
}

export function buildEmissionTree(
  rows: Emission[],
): EmissionTreeRow[] {
  const categories = new Map<string, Map<string, Emission[]>>();

  for (const row of rows) {
    const category =
      categories.get(row.category) ?? new Map<string, Emission[]>();
    const subcategory = category.get(row.subcategory) ?? [];
    subcategory.push(row);
    category.set(row.subcategory, subcategory);
    categories.set(row.category, category);
  }

  return Array.from(categories, ([category, subcategories]) => ({
    id: `category-${category}`,
    kind: 'category',
    title: category,
    subRows: Array.from(subcategories, ([subcategory, leaves]) => ({
      id: `subcategory-${subcategory}`,
      kind: 'subcategory',
      title: subcategory,
      subRows: leaves.map((leaf) => ({
        ...leaf,
        kind: 'source' as const,
      })),
    })),
  }));
}
